apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: chatbot3-may1-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot3-may1-1
  name: chatbot3-may1-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
