apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot3-may1-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot3-may1-1:12dbf35609e8916f6fa20864283787c85f56e5d2@sha256:caa29aca2f14b75bc1f3ba38231ac6fbab054a04998fbdc972175287122afb1b # use pre-built to bootstrap
          name: app-inference
